ALTER TABLE tiendas
  ADD COLUMN IF NOT EXISTS pais TEXT NOT NULL DEFAULT 'Honduras',
  ADD COLUMN IF NOT EXISTS moneda TEXT NOT NULL DEFAULT 'HNL',
  ADD COLUMN IF NOT EXISTS simbolo_moneda TEXT NOT NULL DEFAULT 'L',
  ADD COLUMN IF NOT EXISTS codigo_telefono TEXT NOT NULL DEFAULT '+504';
